import { useRef, useState, useCallback } from "react"
import { debounce } from "lodash"
import { useGLTF, useEnvironment, Text } from "@react-three/drei"
import { useFrame } from "@react-three/fiber"
import { Select } from "@react-three/postprocessing"
import { Price } from "./Price"
import { easing } from "maath"

export function Scene(props) {
  const { nodes, materials } = useGLTF("/kitchen-transformed.glb")
  const env = useEnvironment({ preset: "city" })
  const [hovered, hover] = useState(null)
  const debouncedHover = useCallback(debounce(hover, 30), [])
  const over = (name) => (e) => (e.stopPropagation(), debouncedHover(name))
  const price = { 'Cutting Board': '$25', Room: '$5999', Bowl: '$32', Rug: '$433', Lights: '$77', Chairs: '$255', Table: '$1699', Vases: '$44' }[hovered] ?? '$5999';
  const prodLabelTextRef = useRef();
/*
  useFrame((state, delta) => {
    //easing.damp3(prodLabelTextRef.current.position, [state.pointer.x* 0.2, 0.4 + state.pointer.y *  0.1, 0], 0.3, delta)


  })
*/
  return (
    <>
      <group {...props}>
        <mesh geometry={nodes.bottle.geometry} material={materials.gray} material-envMap={env} />
        <mesh geometry={nodes.walls_1.geometry} material={materials.floor} />
        <mesh geometry={nodes.walls_2.geometry} material={materials.walls} />
        <mesh geometry={nodes.plant_1.geometry} material={materials.potted_plant_01_leaves} />
        <mesh geometry={nodes.plant_2.geometry} material={materials.potted_plant_01_pot} />
      
        <Select enabled={hovered === "Cutting Board"} onClick={over("Cutting Board")} >
          <mesh geometry={nodes.cuttingboard.geometry} material={materials.walls} />
        </Select>

        <Select enabled={hovered === "Bowl"} onClick={over("Bowl")} >
          <mesh geometry={nodes.bowl.geometry} material={materials.walls} />
        </Select>

        <Select enabled={hovered === "Rug"} onClick={over("Rug")} >
          <mesh geometry={nodes.carpet.geometry} material={materials.carpet} />
        </Select>
        <Select enabled={hovered === "Table"} onClick={over("Table")} >
          <mesh geometry={nodes.table.geometry} material={materials.walls} material-envMap={env} material-envMapIntensity={0.5} />
        </Select>
        <Select enabled={hovered === "Chairs"} onClick={over("Chairs")} >
          <mesh geometry={nodes.chairs_1.geometry} material={materials.walls} />
          <mesh geometry={nodes.chairs_2.geometry} material={materials.plastic} material-color="#1a1a1a" material-envMap={env} />
        </Select>
        <Select enabled={hovered === "Vases"} onClick={over("Vases")} >
          <mesh geometry={nodes.vase1.geometry} material={materials.gray} material-envMap={env} />
          <mesh geometry={nodes.vase.geometry} material={materials.gray} material-envMap={env} />
        </Select>
        <Select enabled={hovered === "Lights"} onClick={over("Lights")} >
          <mesh geometry={nodes.lamp_socket.geometry} material={materials.gray} material-envMap={env} />
          <mesh geometry={nodes.lamp.geometry} material={materials.gray} />
          <mesh geometry={nodes.lamp_cord.geometry} material={materials.gray} material-envMap={env} />
        </Select>
        <mesh geometry={nodes.kitchen.geometry} material={materials.walls} />
        <mesh geometry={nodes.sink.geometry} material={materials.chrome} material-envMap={env} />
      </group>
      <Text ref={prodLabelTextRef} anchorX="left" anchorY="middle" position={[-0.5, 0.45, 1]} color="black" fontSize={0.15} font="PlaywriteDESAS-Regular.woff" letterSpacing={-0.05}>
        {hovered ? hovered : "Tap to Select Product"}
      </Text>
      {/** Forward the price to the ticker component */}
      {<Price value={price} position={[-2.5, 0.8, -3.25]} />}
    </>
  )
}

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 kitchen.glb --transform
Files: kitchen.glb [134.46MB] > kitchen-transformed.glb [2.1MB] (98%)
*/
